# Generated by Django 4.1.1 on 2022-10-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'emp',
            },
        ),
        migrations.DeleteModel(
            name='crw',
        ),
    ]
