# Generated by Django 4.1.1 on 2022-10-19 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crview', '0002_employees_delete_crw'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employees',
            table='employe',
        ),
    ]
